### ISSUE TITLE
blank log in page

### ISSUE THREAD

**Issue by brunozhu2** [berta-cms/berta#280]
Hi there ! I just updated to the most recent version of Berta (v. 1.4.1), but when I go to /engine page it appears blank. I've read a previous thread regarding same problem, erased /login.php, but the issue remains.

**Comment by uldisrudzitis** [comment]
Hi, please make sure you have the latest `.htaccess` file https://github.com/berta-cms/berta/blob/master/.htaccess mac users can't see this file by default as it's a system file and is hidden.

**Comment by damienv-hue** [comment]
Hi, I installed the latest version of Berta V2.9.1 and used the windows platform so I was sure that everthing was there. Still I got the issue when you login  " Http failure response for https://maquetist.be/_api/v1/login: 500 OK " I asked my provider to and has confirmed that mod_rewrite is enabled on the server. What's is missing or went wrong
