### ISSUE TITLE
Support for PHP 7.2.19?

### ISSUE THREAD

**Issue by pludmale** [berta-cms/berta#305]
Not an issue per se, but Is there a particular reason anything above 7.2.0 is not supported?

Perhaps I should change a particular file in my local version to support 7.2.19, which is what I have on my server?

**Comment by uldisrudzitis** [comment]
Currently API part of application uses "laravel/lumen-framework": "5.2.*" which is designed to support latest PHP 5 version, anyway it's working fine with PHP 7.1 also.
We are on the way to update all the code and add support for latest PHP versions.

**Comment by TomVDH** [comment]
Hey all -- is there any update about this? I wasn't able to run it on my hosting solution which only offers PHP 7.2.xx at this time. I'm sure Lumen would allow for relative ease of updating?

**Comment by MortenMoxx** [comment]
I usually recomand Bertha to my students online portfolios. It's the perfect tool for them, but the school year is nearing it's end. Is the update eminent?

**Comment by uldisrudzitis** [comment]
Support for PHP 7.2 will be released in production really soon, see https://github.com/berta-cms/berta/pull/347 and currently available in branch https://github.com/berta-cms/berta/tree/php72-support

**Comment by uldisrudzitis** [comment]
PHP 7.2 support is added in Berta v1.8.1 https://github.com/berta-cms/berta/releases/tag/v1.8.1 
Compiled version for download: https://github.com/berta-cms/berta/releases/download/v1.8.1/berta.zip
