### ISSUE TITLE
Releases above 0.8.11b not working

### ISSUE THREAD

**Issue by sam-sept** [berta-cms/berta#343]
Hello, 
first, thank you for your effort!

I tried to install versions above 0.8.11b but nothing works, could you help?

I tried locally or online, with a PHP version below 7.2.

Many thanks!

Sam.

**Comment by uldisrudzitis** [comment]
Try to use the compiled version with all the dependencies inside: https://github.com/berta-cms/berta/releases/download/v1.8.0/berta.zip

**Comment by sam-sept** [comment]
When I put those files in the root directory, I get this error : 

`Warning: fopen(/Applications/MAMP/htdocs/storage/settings.xml): failed to open stream: No such file or directory in /engine/_classes/class.settings.php on line 70

Whoops, looks like something went wrong.
`

Locally and online.

If it's not in the root directory, I just have a
`Not found!`

Thanks.

**Comment by uldisrudzitis** [comment]
Please read carefully the installation instructions https://github.com/berta-cms/berta/wiki/Installation and server requirements, maybe you missed something? Did you create a `storage` folder with write permissions?

**Comment by sam-sept** [comment]
You're right, my mistake was that I hadn't created a `storage` folder.
Then I got a blank login page which is already explained in issue #280 

Many thanks!
