### ISSUE TITLE
no images

### ISSUE THREAD

**Issue by brunozhu2** [berta-cms/berta#356]
Hi ! Thank you so much for the new update, was very looking forward to it !

After upgrading, my pages with images were blank (there was empty space instead), and uploading a new one would just not show up (see attachment, showing 'broken' file). I followed the installation/upgrading instructions, keeping the 'storage' file while having the remaining files/folders replaced.

<img width="639" alt="Screenshot 2020-04-02 at 10 02 19" src="https://user-images.githubusercontent.com/54651255/78224869-90836480-74c9-11ea-9a67-6a6a0ee562a7.png">

**Comment by uldisrudzitis** [comment]
Hello, try the latest compiled version from the link: https://github.com/berta-cms/berta/releases/download/v1.8.3/berta.zip and let me know how it goes.

**Comment by brunozhu2** [comment]
hi ! the issue remains

**Comment by uldisrudzitis** [comment]
Probably you have some issues with existing storage files. Backup your old storage and try to use new version with the empty storage folder. Is it working that way?

**Comment by brunozhu2** [comment]
I double-checked the 'permissions' of storage folder and reticked all boxes. is working now. Thank you !
