### ISSUE TITLE
warning sign on phone browser

### ISSUE THREAD

**Issue by brunozhu2** [berta-cms/berta#357]
Hi again ! 

Was just looking at my website on phone browser and a warning is on the top of the page. I can't select it hence the screenshots. It doesn't show when I'm browsing on my desktop*

*here's copy paste:

Warning: count(): Parameter must be an array or an object that implements Countable in /storage/cache/39276a6d9d8a355eef6eea3ecc77b339468ba903.file.template.tpl.php on line 340

![IMG_1495](https://user-images.githubusercontent.com/54651255/78236868-e3b1e300-74da-11ea-9fad-fea089220225.PNG)
![IMG_1496](https://user-images.githubusercontent.com/54651255/78236873-e4e31000-74da-11ea-8574-1813e5d4fc67.PNG)

**Comment by uldisrudzitis** [comment]
Just fixed this in v1.8.4
Compiled version: https://github.com/berta-cms/berta/releases/download/v1.8.4/berta.zip
