### ISSUE TITLE
Fresh installation won't pass by engine/login: api/v1 -- ERROR 500

### ISSUE THREAD

**Issue by TomVDH** [berta-cms/berta#379]
Hey all, 

The problem's essentially in the title. Fresh install of Berta, all folders made and permissions set. Runs on a server with PHP 7.3.17. 

On loading the main URL, I already see a red error loading bar saying 'Server error or API not found'

On the /engine page, I then get this on trying to log in.

On Chrome:
`Http failure response for https://photo.tvdhdvt.xyz/_api/v1/login: 500 OK`

On Firefox:
`Http failure response for https://photo.tvdhdvt.xyz/_api/v1/login: 500 Internal Server Error`

I am unsure what's going on -- can anyone pitch in?

**Comment by uldisrudzitis** [comment]
Berta is currently tested and works fine in PHP 7.2
Support for PHP 7.3, 7.4 is in our plans.

**Comment by uldisrudzitis** [comment]
Good news, just released v1.9.0 https://github.com/berta-cms/berta/releases/tag/v1.9.0 with PHP >= 7.3 support, including support for PHP 7.4 and PHP 8.0.

**Comment by bartVPB** [comment]
Hi, 
I 've installed Berta v1.9 on a server with PHP 7.4 and I'm having the same issue: _api/v1/login: 500 Internal Server Error on Safari and Chrome.
Can I get some help, please?

**Comment by uldisrudzitis** [comment]
Hi, can you post some error log output?

**Comment by bartVPB** [comment]
I found my error log, but I don't know which part of the log output you need. It's quite extensive.

**Comment by uldisrudzitis** [comment]
Give me a couple of last error stacks, your will find the date timestamp in front of error messages.

**Comment by bartVPB** [comment]
Thank you. Hope this is the right bit...

[Fri Jan 07 08:55:11.335463 2022] [error] [pid 20752] apache2_util.c(273): [client 157.90.177.232:0] [client 157.90.177.232] ModSecurity: Access denied with code 403 (phase 2). Pattern match "(?i:(?:c(?:o(?:n(?:t(?:entsmartz|actbot/)|cealed defense|veracrawler)|mpatible(?: ;(?: msie|\\\\.)|-)|py(?:rightcheck|guard)|re-project/1.0)|h(?:ina(?: local browse 2\\\\.|claw)|e(?:rrypicker|esebot))|rescent internet toolpak)|w(?:e(?:b(?: (?:downloader|by ..." at REQUEST_HEADERS:User-Agent. [file "/usr/local/httpd/conf/modsecurity-crs/activated-rules/modsecurity_crs_35_bad_robots.conf"] [line "27"] [id "990012"] [rev "2"] [msg "Rogue web site crawler"] [data "BLEXBot"] [severity "WARNING"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/AUTOMATION/MALICIOUS"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "peth.gc-m.be"] [uri "/robots.txt"] [unique_id "Ydfx3@lYMspRfjJE95N4wQAAAKs"]
[Fri Jan 07 08:56:56.981713 2022] [error] [pid 24256] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/index.php
[Fri Jan 07 08:56:58.118999 2022] [error] [pid 20752] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/dev
[Fri Jan 07 08:57:09.367580 2022] [error] [pid 20752] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/old
[Fri Jan 07 08:57:15.684369 2022] [error] [pid 24256] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/test
[Fri Jan 07 08:57:21.951152 2022] [error] [pid 20752] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/demo
[Fri Jan 07 08:57:23.148973 2022] [error] [pid 20752] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/shop
[Fri Jan 07 08:57:24.351778 2022] [error] [pid 20752] mod_authz_core.c(882): [client 172.98.87.242:0] AH01630: client denied by server configuration: /data/sites/web/gc-mbe/www/store

**Comment by uldisrudzitis** [comment]
This kind of error is not directly related to Berta code. This error comes from Apache ModSecurity extension. You can ask your server support staff to configure this extensions to prevent this error.

**Comment by bartVPB** [comment]
Thank you for the quick response.
