### ISSUE TITLE
Upgrade won't work, wrong path? 

### ISSUE THREAD

**Issue by victorboykocom** [berta-cms/berta#407]
Fresh install of berta v1.8.11 over old berta 0.8.11b.
old berta working perfectly.

new one not working giving this if I navigate to my site (see below).

my shared server path is /victorboyko.com/www/

Warning: require_once(/home/u12454/victorboyko.com/www/_api_app/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/u12454/victorboyko.com/www/_api_app/bootstrap/app.php on line 3

Fatal error: require_once(): Failed opening required '/home/u12454/victorboyko.com/www/_api_app/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/u12454/victorboyko.com/www/_api_app/bootstrap/app.php on line 3

**Comment by uldisrudzitis** [comment]
Hello,
did you use this precompiled version https://github.com/berta-cms/berta/releases/download/v1.8.11/berta.zip ?
