### ISSUE TITLE
Issue with Templates installation

### ISSUE THREAD

**Issue by mlparedes** [berta-cms/berta#408]
Hello,
I have successfully installed Release [v1.8.11] in my server and all works well.
However I cannot make the new Templates installation work: I upload the Themes folder as a ZIP to my freshly installed _themes directory and unpack them. I then run my site for the 1st time to configure and get an Error 500 in the configuration screen. I cannot progress beyond that.
It all runs fine if I do not upload the Themes. Am I missing something?
Thanks in advance,
Miguel

**Comment by uldisrudzitis** [comment]
Can you show me the theme you are trying to install? 👀

**Comment by mlparedes** [comment]
Thanks for the quick response. I am trying to install the Madrid theme included in the themes directory.

**Comment by uldisrudzitis** [comment]
Berta themes are available in this repository: https://github.com/berta-cms/themes
Make sure `_themes` directory structure is following:

./_themes
├── capetown
│   ├── blog.contacts.xml
│   ├── blog.products.xml
│   ├── blog.story.xml
│   ├── blog.team.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.messy.xml
│   └── settings.xml
├── capetown.png
├── jaipur
│   ├── blog.contacts.xml
│   ├── blog.hit-the-road.xml
│   ├── blog.home.xml
│   ├── blog.solitude.xml
│   ├── blog.we-work.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.white.xml
│   └── settings.xml
├── jaipur.png
├── kyoto
│   ├── blog.about.xml
│   ├── blog.fashion.xml
│   ├── blog.home.xml
│   ├── blog.shows.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.white.xml
│   └── settings.xml
├── kyoto.png
├── madrid
│   ├── blog.bio.xml
│   ├── blog.photography.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.messy.xml
│   └── settings.xml
├── madrid.png
├── newyork
│   ├── blog.contacts.xml
│   ├── blog.portfolio.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.messy.xml
│   └── settings.xml
├── newyork.png
├── riga
│   ├── blog.about.xml
│   ├── blog.home.xml
│   ├── blog.nature.xml
│   ├── blog.streets.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.messy.xml
│   └── settings.xml
├── riga.png
├── sydney
│   ├── blog.about.xml
│   ├── blog.exhibitions.xml
│   ├── blog.portfolio.xml
│   ├── media
│   ├── sections.xml
│   ├── settings.messy.xml
│   └── settings.xml
└── sydney.png

Then login to your Berta and select theme from `Settings -> Themes -> Choose Theme` menu.
This should work fine.

**Comment by mlparedes** [comment]
Thanks for the response. I have populated the  _themes directory as you noted and the installation goes smoothly. However these is no option in Berta to select 'Themes' in the Berta Settings menu. Only 'Templates' can be selected (and only the default 4 templates are available)
Is it possible that there is a mixup between the _themes and _templates here?
Thanks for your help!

**Comment by uldisrudzitis** [comment]
Try to reload the page and check if `Themes` menu item appears. I couldn't reproduce your issue, possibly your server is configured somehow differently.

**Comment by mlparedes** [comment]
It is working now - I reloaded the page as you suggested and the Themes menu item appeared. 
Thank you very much for your help!
