### ISSUE TITLE
Installation instructions are incorrect or incomplete

### ISSUE THREAD

**Issue by rogeriod** [berta-cms/berta#409]
Installation instructions are out of date and do not work - they should be validated on a clean webserver or virtual machine.

Install produces error page with the following code:

```
Warning: require_once(/var/www/html/_api_app/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/_api_app/bootstrap/app.php on line 3

Fatal error: require_once(): Failed opening required '/var/www/html/_api_app/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/_api_app/bootstrap/app.php on line 3
```

**Comment by uldisrudzitis** [comment]
Looks like `vendor` folder is not created. Did you run composer? If not, try the compiled version from here https://github.com/berta-cms/berta/releases/download/v1.9.3/berta.zip
