### ISSUE TITLE
engine/login.php doesn't work

### ISSUE THREAD

**Issue by alexiske** [berta-cms/berta#411]
I upload latest version of berta on my server (php7.2) following the indications but when i'm trying to log in, nothing happen... I'm in front of a blank page.

**Comment by uldisrudzitis** [comment]
Hello,
make sure `.htaccess` (https://github.com/berta-cms/berta/blob/master/.htaccess) file is in the website root directory.

**Comment by alexiske** [comment]
It works, thanks!!
