### ISSUE TITLE
upgraded to latest version + lots of non well formed numeric values error notices

### ISSUE THREAD

**Issue by ggggggr** [berta-cms/berta#416]
I just upgraded Berta version, and I'm getting lots of these red notices in all sections with images:

Notice: A non well formed numeric value encountered in /homepages/45/d707779343/htdocs/berta/_api_app/app/Shared/ImageHelpers.php on line XXX

**Comment by uldisrudzitis** [comment]
Please check your PHP version, should be PHP >= 5.6.4 and < 7.4

**Comment by ggggggr** [comment]
I'm using php 7.3, it went away by entering into each section with images(and the red notices on top of the page) and changing images size from medium to large.
