### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by brunozhu2** [berta-cms/berta#445]
Hi there,

Thank you so much for the new version ! I've just updated to v.1.9.3 and the following error appeared:

Warning: file_get_contents(/customers/0/2/3/brunozhu.com/httpd.www/_api_app/.env): failed to open stream: No such file or directory in /_api_app/vendor/vlucas/phpdotenv/src/Store/File/Reader.php on line 73

Looking forward to hearing from you.

**Comment by uldisrudzitis** [comment]
Please create an empty file named `.env` in folder  `_api_app` or copy it from your previous Berta version. Will take a look at this case, the expected behaviour is that application itself creates this file if it doesn't exist.
