### ISSUE TITLE
php issue

### ISSUE THREAD

**Issue by andreawilkinson** [berta-cms/berta#446]
I get this issue after instal: 
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 5.5.38. in /home/andrewe85/domains/dementialabconference.com/public_html/Residue-of-Interaction-2022/_api_app/vendor/composer/platform_check.php on line 25

**Comment by uldisrudzitis** [comment]
PHP 5.5 version is outdated (see https://www.php.net/supported-versions.php) and is not supported by Berta.
See install requirements: https://github.com/berta-cms/berta/wiki/Installation
You should update you PHP version to the latest stable version on server. Contact you hosting service support to assist you if you are not able to switch the version in hosting control panel.
