### ISSUE TITLE
_api/v1/login: 500 OK

### ISSUE THREAD

**Issue by urbelt2** [berta-cms/berta#447]
After installing I get the error when trying to login for the first time:

Http failure response for https://urbelt.kapsi.fi/_api/v1/login: 500 OK

Server error log says this:

urbelt.kapsi.fi E0QXlw+RdHI Wed Nov 24 13:59:29 2021 error [pid 17185:tid 129211513538304] core.c(3878): [client 188.116.59.142:0] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

Php version is 7.4.26

**Comment by ggggggr** [comment]
I'm also getting this error now, and cannot log in:

Http failure response for http://gabriellatorr.es/_api/v1/login: 500 Internal Server Error

**Comment by urbelt2** [comment]
Seems the developer is not very interested in fixing this issue.

**Comment by uldisrudzitis** [comment]
Seems like you are not using the production build version of source code, see https://github.com/berta-cms/berta/wiki/Production-build

The easiest way is to download and extract berta.zip file attached to the Berta release https://github.com/berta-cms/berta/releases/latest that contains the read to go compiled version
