### ISSUE TITLE
Outdated PHP 7.3 version is giving me this error

### ISSUE THREAD

**Issue by ggggggr** [berta-cms/berta#450]
Fatal error: Uncaught ErrorException: Undefined variable: version in /homepages/45/d707779343/htdocs/berta/_api_app/vendor/sentry/sentry/lib/Raven/Client.php:1551 Stack trace: #0 /homepages/45/d707779343/htdocs/berta/_api_app/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined varia...', '/homepages/45/d...', 1551, Array) #1 /homepages/45/d707779343/htdocs/berta/_api_app/vendor/sentry/sentry/lib/Raven/Client.php(1551): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined varia...', '/homepages/45/d...', 1551, Array) #2 /homepages/45/d707779343/htdocs/berta/_api_app/vendor/sentry/sentry/lib/Raven/Client.php(910): Raven_Client::cleanup_php_version() #3 /homepages/45/d707779343/htdocs/berta/_api_app/vendor/sentry/sentry/lib/Raven/Client.php(686): Raven_Client->capture(Array, Array, NULL) #4 /homepages/45/d707779343/htdocs/berta/_api_app/app/Exceptions/Handler.php(37): Raven_Client->captureException(Object(ErrorException)) #5 /homepage in /homepages/45/d707779343/htdocs/berta/_api_app/vendor/sentry/sentry/lib/Raven/Client.php on line 1551

**Comment by uldisrudzitis** [comment]
At the moment current version v1.9.3 supports PHP 7.3.
Try to install your berta from this compiled version -> https://github.com/berta-cms/berta/releases/download/v1.9.3/berta.zip
