### ISSUE TITLE
After Installation white Screen

### ISSUE THREAD

**Issue by MateBer** [berta-cms/berta#461]
Hello There,
What it means? After the installation from the new berta version i see just a white screen. Cant login! Any idears. Best Mate

**Comment by uldisrudzitis** [comment]
Seems like you are not using the production build version of source code, see https://github.com/berta-cms/berta/wiki/Production-build

The easiest way is to download and extract berta.zip file attached to the Berta release https://github.com/berta-cms/berta/releases/latest that contains the ready to go compiled version
