### ISSUE TITLE
error help - errno=21 v. 1.9.3

### ISSUE THREAD

**Issue by ggggggr** [berta-cms/berta#467]
Thanks so much for the php update. I just upgraded to version 1.9.3. and first I got [this](https://github.com/berta-cms/berta/issues/445) error, made sure the .env file was there, and now I'm getting this error: 

Notice: file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory in /homepages/45/d707779343/htdocs/berta/_api_app/vendor/vlucas/phpdotenv/src/Store/File/Reader.php on line 73

I'm using PHP 8.0

**Comment by ggggggr** [comment]
I also tried the login, and I'm getting this error: 

Http failure response for http://gabriellatorr.es/_api/v1/login: 500 Internal Server Error

**Comment by ggggggr** [comment]
UPDATE: I changed back to the PHP 7.3 outdated version, and the website loads... not sure how to handle this, please help me make it work for updated PHP versions

**Comment by uldisrudzitis** [comment]
Make sure you have a file called `.env` under '_api_app' folder. You will find the example file in the same folder called `.env.example`. Usually this file is created automatically, but fails when there is no write permissions there

**Comment by ggggggr** [comment]
@uldisrudzitis thanx for replying, I just re uploaded the latest version files (all those included in the source code) and now I'm getting this error, not sure what else to do to make it work: 

Warning: require_once(/homepages/45/xxxxxxxxxx/htdocs/berta/_api_app/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /homepages/45/xxxxxxxxxx/htdocs/berta/_api_app/bootstrap/app.php on line 3

**Comment by uldisrudzitis** [comment]
@ggggggr did you use this archive https://github.com/berta-cms/berta/releases/download/v1.9.3/berta.zip ?

**Comment by ggggggr** [comment]
@uldisrudzitis thanx, I deleted everything and installed the contents of the link you sent (https://github.com/berta-cms/berta/releases/download/v1.9.3/berta.zip) ... its displaying the website now, also working with a newer php version (PHP 8.0). 

The only problem I have now is that the login page (http://domain/engine) is completely blank/white

**Comment by uldisrudzitis** [comment]
Make sure `.htaccess` file in the root folder is updated from the latest version. Files with the dot `.` in the front of filename usually are hidden, so make sure the contents inside are from the latest version.

**Comment by ggggggr** [comment]
@uldisrudzitis now it has the latest version, I see the webpage and when I try to enter with the user/pass I get this error:

Http failure response for http://gabriellatorr.es/_api/v1/login: 500 Internal Server Error

You said in other issue that its related to the production build, not sure how to fix this. Thanx

**Comment by uldisrudzitis** [comment]
@ggggggr Looks like it is the `.env` file case I mentioned earlier. Error log could be more helpful to detect the problem.

**Comment by ggggggr** [comment]
@uldisrudzitis thanks for the quick replies... so ever since you wrote about creating the .env, I created an empty .env, but it wasn't working... I now replaced it with the older .env file, and now it works, these are the contents of the older .env: 

APP_ENV=production
APP_DEBUG=false
CACHE_DRIVER=file
APP_KEY=25e8aba1-8c94-467e-a580-db7cbecd14f3
APP_ID=b3a37ad7-f900-4efc-af52-17afdacb34f7
API_PREFIX=_api
SENTRY_DSN=
SENTRY_PUBLIC_DSN=
