### ISSUE TITLE
Oops! An Error Occurred The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by ggggggr** [berta-cms/berta#507]
Hello,

For unknown reasons, 2 sections of my Berta website that once displayed properly are now displaying the following:
http://gabriellatorr.es/eightball/ + http://gabriellatorr.es/itwjgbps-filter/

<img width="1328" alt="Screenshot 2023-04-17 at 16 00 23" src="https://user-images.githubusercontent.com/30274338/232506880-d1df53d1-8066-49fa-90a3-e979428f7d1b.png">

The only thing they have in common is displaying single entry videos, if you have any idea as to how to resolve, please let me know, thank you so much

**Comment by ggggggr** [comment]
Tried to make the post again, I've been using the Messy template > gallery type: column > fullscreen: no > image size: large with success... In these particular problematic posts I've changed the image size: medium, and I'm afraid that's what causing the 'Internal Server Error'

**Comment by uldisrudzitis** [comment]
@ggggggr check the `settings -> media` input fields, there should be integer values only without `px` at the end.

**Comment by ggggggr** [comment]
Got it, thanks so much <3
