### ISSUE TITLE
mod_rewrite

### ISSUE THREAD

**Issue by rupraph** [berta-cms/berta#84]
Hi !

My host forbids to allow mod_rewrite for .htaccess. What are my options, because I am stuck with 500 errors....

Thanks

**Comment by uldisrudzitis** [comment]
Hello,
Berta works fine without .htaccess file, you can simply remove it. You will only loose SEO friendly urls.

**Comment by rupraph** [comment]
it seems that on my host I have to use the htaccess file to enable php5. If I don't, nothing works. So I kept it, containing only "php 1" (which activates php5 on my host).
Using this, the website seems to work, but no display. It get a blank page on any page.....

**Comment by uldisrudzitis** [comment]
What's the http status code? Check your php or web server error log for more detailed info.

**Comment by rupraph** [comment]
Where can I find this ? 
I just saw my host is running php 5.1.3 . should it work with this already old php verison ?

**Comment by uldisrudzitis** [comment]
Well... it's almost 10 years old PHP version, I recommend you to ask your hosting provider for more updated version and where your error logs are located.

**Comment by rupraph** [comment]
by changing the php line in the htaccess file (only containig this line), I finally activated php 5.6.8.

when i try to go to engine with a f resh install of berta, iget:

Error: Call to undefined function mb_ereg_replace() in /engine/_classes/class.bertautils.php on line 108

**Comment by rupraph** [comment]
http://rup.ert.free.fr/version-php.php

**Comment by uldisrudzitis** [comment]
Multibyte String extension should be enabled: http://php.net/manual/en/mbstring.installation.php

**Comment by rupraph** [comment]
ok. thank you. I will try to enable it with my host.
